export const TASKS_LIST_REQUEST = 'TASKS_LIST_REQUEST';
export const TASKS_LIST_SUCCESS = 'TASKS_LIST_SUCCESS';
export const TASKS_LIST_FAIL = 'TASKS_LIST_FAIL';

export const TASKS_CREATE_REQUEST = 'TASKS_CREATE_REQUEST';
export const TASKS_CREATE_SUCCESS = 'TASKS_CREATE_SUCCESS';
export const TASKS_CREATE_FAIL = 'TASKS_CREATE_FAIL';